### PR TITLE
[wip] Add Windows library

### PR DESCRIPTION
**Pull request by sodre**
Checklist:
  - [ ] run test for windows
  - [ ] PRPACK library is not being built at the moment
  - [ ] Use %LIBRARY_INC% and %LIBRARY_LIB% instead of winclude and wlib
  - [ ] rebase -i

### CODE REVIEW

**Comment by vtraag** [comment]
@sodre, I see that you are trying to get this to work. This is not yet functional? Perhaps I could help you out? I think it would be very good if we can provide Windows support for `igraph` from `conda-forge`.

I have a branch specifically for Windows of [`igraph`](https://github.com/vtraag/igraph/commits/release-0.7-win) and of [`python-igraph`](https://github.com/vtraag/python-igraph) that I use to provide a [binary Windows](https://anaconda.org/vtraag/python-igraph) version  for Anaconda. The patches are quite straightforward I think (although the actual commits are perhaps a bit more messy because of some experimentation).

**Comment by sodre** [comment]
I haven't touched this branch in a long time. please feel free to open a new PR and ping me directly once it is ready to merge.

**Comment by Tata17** [comment]
@vtraag Hello there! Wondering if you are planning to continue working on the Windows support for igraph and python-igraph into conda-forge?

**Comment by vtraag** [comment]
@Tata17 yes, but it will be a somewhat longer process however.

It requires a new release of `python-igraph` that is correctly compilable on Windows. Currently, it is not possible to include `python-igraph` in `conda-forge` because its dependency `igraph` (the C core library) isn't available on Windows currently. We are therefore first working on a new release of `igraph`, then work towards a new release of `python-igraph`, which should be included in `conda-forge`. For the moment, you can install `python-igraph` on Windows from my [personal channel](https://anaconda.org/vtraag/python-igraph), `conda install -c vtraag python-igraph`.

**Comment by sodre** [comment]
Hi folks,

Can we migrate your patches to this (and I graph) repos? We can restrict the patch to windows if necessary.

**Comment by vtraag** [comment]
@sodre yes, that would be possible, and it's what I had in mind initially. 

But I prefer to dedicate my time to contributing to a new release of `igraph` followed by a new release of `python-igraph`. The planning at the moment is to get a new release of `igraph` out around August, we have not yet settled on a date for `python-igraph`. I believe that is a preferable route to supporting Windows properly.

**Comment by Tata17** [comment]
> @Tata17 yes, but it will be a somewhat longer process however.



> @Tata17 yes, but it will be a somewhat longer process however.
> 
> It requires a new release of `python-igraph` that is correctly compilable on Windows. Currently, it is not possible to include `python-igraph` in `conda-forge` because its dependency `igraph` (the C core library) isn't available on Windows currently. We are therefore first working on a new release of `igraph`, then work towards a new release of `python-igraph`, which should be included in `conda-forge`. For the moment, you can install `python-igraph` on Windows from my [personal channel](https://anaconda.org/vtraag/python-igraph), `conda install -c vtraag python-igraph`.
> 
> It would also be possible using manual patches, as suggested above, but this makes the whole packaging quite obscure (and also the versioning quite unclear).

@vtraag thanks a lot for the candid answer

**Comment by sodre** [comment]
closed by #15

**Pull request closed without merging**
