### PR TITLE
Rebuild for libxml2 2.11

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes #51

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
OSX-ARM64 error is:
```
: && $BUILD_PREFIX/bin/arm64-apple-darwin20.0.0-clang++ -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/igraph-0.10.4 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -O3 -DNDEBUG -flto=thin -isysroot /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -mmacosx-version-min=11.0 -dynamiclib -Wl,-headerpad_max_install_names -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,$PREFIX/lib -L$PREFIX/lib   -compatibility_version 3.0.0 -current_version 3.0.0 -o src/libigraph.3.0.0.dylib -install_name @rpath/libigraph.3.dylib vendor/plfit/CMakeFiles/plfit_vendored.dir/gss.c.o vendor/plfit/CMakeFiles/plfit_vendored.dir/hzeta.c.o vendor/plfit/CMakeFiles/plfit_vendored.dir/kolmogorov.c.o vendor/plfit/CMakeFiles/plfit_vendored.dir/lbfgs.c.o vendor/plfit/CMakeFiles/plfit_vendored.dir/mt.c.o vendor/plfit/CMakeFiles/plfit_vendored.dir/options.c.o vendor/plfit/CMakeFiles/plfit_vendored.dir/platform.c.o vendor/plfit/CMakeFiles/plfit_vendored.dir/plfit.c.o vendor/plfit/CMakeFiles/plfit_vendored.dir/plfit_error.c.o vendor/plfit/CMakeFiles/plfit_vendored.dir/rbinom.c.o vendor/plfit/CMakeFiles/plfit_vendored.dir/sampling.c.o src/isomorphism/bliss/CMakeFiles/bliss.dir/defs.cc.o src/isomorphism/bliss/CMakeFiles/bliss.dir/graph.cc.o src/isomorphism/bliss/CMakeFiles/bliss.dir/heap.cc.o src/isomorphism/bliss/CMakeFiles/bliss.dir/orbit.cc.o src/isomorphism/bliss/CMakeFiles/bliss.dir/partition.cc.o src/isomorphism/bliss/CMakeFiles/bliss.dir/uintseqhash.cc.o src/isomorphism/bliss/CMakeFiles/bliss.dir/utils.cc.o src/cliques/cliquer/CMakeFiles/cliquer.dir/cliquer.c.o src/cliques/cliquer/CMakeFiles/cliquer.dir/cliquer_graph.c.o src/cliques/cliquer/CMakeFiles/cliquer.dir/reorder.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_add.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_amd.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_chol.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_cholsol.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_compress.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_counts.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_cumsum.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_dfs.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_dmperm.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_droptol.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_dropzeros.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_dupl.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_entry.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_ereach.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_etree.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_fkeep.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_gaxpy.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_happly.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_house.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_ipvec.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_leaf.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_load.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_lsolve.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_ltsolve.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_lu.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_lusol.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_malloc.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_maxtrans.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_multiply.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_norm.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_permute.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_pinv.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_post.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_pvec.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_qr.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_qrsol.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_randperm.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_reach.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_scatter.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_scc.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_schol.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_spsolve.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_sqr.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_symperm.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_tdfs.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_transpose.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_updown.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_usolve.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_util.c.o vendor/cs/CMakeFiles/cxsparse_vendored.dir/cs_utsolve.c.o vendor/pcg/CMakeFiles/pcg.dir/pcg-advance-64.c.o vendor/pcg/CMakeFiles/pcg.dir/pcg-advance-128.c.o vendor/pcg/CMakeFiles/pcg.dir/pcg-output-32.c.o vendor/pcg/CMakeFiles/pcg.dir/pcg-output-64.c.o vendor/pcg/CMakeFiles/pcg.dir/pcg-output-128.c.o vendor/pcg/CMakeFiles/pcg.dir/pcg-rngs-64.c.o vendor/pcg/CMakeFiles/pcg.dir/pcg-rngs-128.c.o src/centrality/prpack/CMakeFiles/prpack.dir/prpack_base_graph.cpp.o src/centrality/prpack/CMakeFiles/prpack.dir/prpack_igraph_graph.cpp.o src/centrality/prpack/CMakeFiles/prpack.dir/prpack_preprocessed_ge_graph.cpp.o src/centrality/prpack/CMakeFiles/prpack.dir/prpack_preprocessed_gs_graph.cpp.o src/centrality/prpack/CMakeFiles/prpack.dir/prpack_preprocessed_scc_graph.cpp.o src/centrality/prpack/CMakeFiles/prpack.dir/prpack_preprocessed_schur_graph.cpp.o src/centrality/prpack/CMakeFiles/prpack.dir/prpack_result.cpp.o src/centrality/prpack/CMakeFiles/prpack.dir/prpack_solver.cpp.o src/centrality/prpack/CMakeFiles/prpack.dir/prpack_utils.cpp.o src/CMakeFiles/igraph.dir/core/array.c.o src/CMakeFiles/igraph.dir/core/buckets.c.o src/CMakeFiles/igraph.dir/core/cutheap.c.o src/CMakeFiles/igraph.dir/core/dqueue.c.o src/CMakeFiles/igraph.dir/core/error.c.o src/CMakeFiles/igraph.dir/core/estack.c.o src/CMakeFiles/igraph.dir/core/fixed_vectorlist.c.o src/CMakeFiles/igraph.dir/core/genheap.c.o src/CMakeFiles/igraph.dir/core/grid.c.o src/CMakeFiles/igraph.dir/core/heap.c.o src/CMakeFiles/igraph.dir/core/indheap.c.o src/CMakeFiles/igraph.dir/core/interruption.c.o src/CMakeFiles/igraph.dir/core/marked_queue.c.o src/CMakeFiles/igraph.dir/core/matrix.c.o src/CMakeFiles/igraph.dir/core/matrix_list.c.o src/CMakeFiles/igraph.dir/core/memory.c.o src/CMakeFiles/igraph.dir/core/printing.c.o src/CMakeFiles/igraph.dir/core/progress.c.o src/CMakeFiles/igraph.dir/core/psumtree.c.o src/CMakeFiles/igraph.dir/core/set.c.o src/CMakeFiles/igraph.dir/core/sparsemat.c.o src/CMakeFiles/igraph.dir/core/stack.c.o src/CMakeFiles/igraph.dir/core/statusbar.c.o src/CMakeFiles/igraph.dir/core/strvector.c.o src/CMakeFiles/igraph.dir/core/trie.c.o src/CMakeFiles/igraph.dir/core/vector.c.o src/CMakeFiles/igraph.dir/core/vector_list.c.o src/CMakeFiles/igraph.dir/core/vector_ptr.c.o src/CMakeFiles/igraph.dir/math/complex.c.o src/CMakeFiles/igraph.dir/math/safe_intop.c.o src/CMakeFiles/igraph.dir/math/utils.c.o src/CMakeFiles/igraph.dir/linalg/arpack.c.o src/CMakeFiles/igraph.dir/linalg/blas.c.o src/CMakeFiles/igraph.dir/linalg/eigen.c.o src/CMakeFiles/igraph.dir/linalg/lapack.c.o src/CMakeFiles/igraph.dir/random/random.c.o src/CMakeFiles/igraph.dir/random/rng_glibc2.c.o src/CMakeFiles/igraph.dir/random/rng_mt19937.c.o src/CMakeFiles/igraph.dir/random/rng_pcg32.c.o src/CMakeFiles/igraph.dir/random/rng_pcg64.c.o src/CMakeFiles/igraph.dir/graph/adjlist.c.o src/CMakeFiles/igraph.dir/graph/attributes.c.o src/CMakeFiles/igraph.dir/graph/basic_query.c.o src/CMakeFiles/igraph.dir/graph/caching.c.o src/CMakeFiles/igraph.dir/graph/cattributes.c.o src/CMakeFiles/igraph.dir/graph/graph_list.c.o src/CMakeFiles/igraph.dir/graph/iterators.c.o src/CMakeFiles/igraph.dir/graph/type_common.c.o src/CMakeFiles/igraph.dir/graph/type_indexededgelist.c.o src/CMakeFiles/igraph.dir/graph/visitors.c.o src/CMakeFiles/igraph.dir/constructors/adjacency.c.o src/CMakeFiles/igraph.dir/constructors/atlas.c.o src/CMakeFiles/igraph.dir/constructors/basic_constructors.c.o src/CMakeFiles/igraph.dir/constructors/circulant.c.o src/CMakeFiles/igraph.dir/constructors/de_bruijn.c.o src/CMakeFiles/igraph.dir/constructors/famous.c.o src/CMakeFiles/igraph.dir/constructors/full.c.o src/CMakeFiles/igraph.dir/constructors/generalized_petersen.c.o src/CMakeFiles/igraph.dir/constructors/kautz.c.o src/CMakeFiles/igraph.dir/constructors/lattices.c.o src/CMakeFiles/igraph.dir/constructors/lcf.c.o src/CMakeFiles/igraph.dir/constructors/linegraph.c.o src/CMakeFiles/igraph.dir/constructors/prufer.c.o src/CMakeFiles/igraph.dir/constructors/regular.c.o src/CMakeFiles/igraph.dir/constructors/trees.c.o src/CMakeFiles/igraph.dir/games/barabasi.c.o src/CMakeFiles/igraph.dir/games/callaway_traits.c.o src/CMakeFiles/igraph.dir/games/citations.c.o src/CMakeFiles/igraph.dir/games/correlated.c.o src/CMakeFiles/igraph.dir/games/degree_sequence_vl/gengraph_degree_sequence.cpp.o src/CMakeFiles/igraph.dir/games/degree_sequence_vl/gengraph_graph_molloy_hash.cpp.o src/CMakeFiles/igraph.dir/games/degree_sequence_vl/gengraph_graph_molloy_optimized.cpp.o src/CMakeFiles/igraph.dir/games/degree_sequence_vl/gengraph_mr-connected.cpp.o src/CMakeFiles/igraph.dir/games/degree_sequence.c.o src/CMakeFiles/igraph.dir/games/dotproduct.c.o src/CMakeFiles/igraph.dir/games/erdos_renyi.c.o src/CMakeFiles/igraph.dir/games/establishment.c.o src/CMakeFiles/igraph.dir/games/forestfire.c.o src/CMakeFiles/igraph.dir/games/grg.c.o src/CMakeFiles/igraph.dir/games/growing_random.c.o src/CMakeFiles/igraph.dir/games/islands.c.o src/CMakeFiles/igraph.dir/games/k_regular.c.o src/CMakeFiles/igraph.dir/games/preference.c.o src/CMakeFiles/igraph.dir/games/recent_degree.c.o src/CMakeFiles/igraph.dir/games/sbm.c.o src/CMakeFiles/igraph.dir/games/static_fitness.c.o src/CMakeFiles/igraph.dir/games/tree.c.o src/CMakeFiles/igraph.dir/games/watts_strogatz.c.o src/CMakeFiles/igraph.dir/centrality/betweenness.c.o src/CMakeFiles/igraph.dir/centrality/centrality_other.c.o src/CMakeFiles/igraph.dir/centrality/centralization.c.o src/CMakeFiles/igraph.dir/centrality/closeness.c.o src/CMakeFiles/igraph.dir/centrality/coreness.c.o src/CMakeFiles/igraph.dir/centrality/eigenvector.c.o src/CMakeFiles/igraph.dir/centrality/hub_authority.c.o src/CMakeFiles/igraph.dir/centrality/pagerank.c.o src/CMakeFiles/igraph.dir/centrality/truss.cpp.o src/CMakeFiles/igraph.dir/centrality/prpack.cpp.o src/CMakeFiles/igraph.dir/cliques/cliquer_wrapper.c.o src/CMakeFiles/igraph.dir/cliques/cliques.c.o src/CMakeFiles/igraph.dir/cliques/maximal_cliques.c.o src/CMakeFiles/igraph.dir/cliques/glet.c.o src/CMakeFiles/igraph.dir/community/community_misc.c.o src/CMakeFiles/igraph.dir/community/edge_betweenness.c.o src/CMakeFiles/igraph.dir/community/fast_modularity.c.o src/CMakeFiles/igraph.dir/community/fluid.c.o src/CMakeFiles/igraph.dir/community/infomap/infomap_FlowGraph.cc.o src/CMakeFiles/igraph.dir/community/infomap/infomap_Greedy.cc.o src/CMakeFiles/igraph.dir/community/infomap/infomap.cc.o src/CMakeFiles/igraph.dir/community/label_propagation.c.o src/CMakeFiles/igraph.dir/community/leading_eigenvector.c.o src/CMakeFiles/igraph.dir/community/leiden.c.o src/CMakeFiles/igraph.dir/community/louvain.c.o src/CMakeFiles/igraph.dir/community/modularity.c.o src/CMakeFiles/igraph.dir/community/optimal_modularity.c.o src/CMakeFiles/igraph.dir/community/spinglass/clustertool.cpp.o src/CMakeFiles/igraph.dir/community/spinglass/NetDataTypes.cpp.o src/CMakeFiles/igraph.dir/community/spinglass/NetRoutines.cpp.o src/CMakeFiles/igraph.dir/community/spinglass/pottsmodel_2.cpp.o src/CMakeFiles/igraph.dir/community/walktrap/walktrap_communities.cpp.o src/CMakeFiles/igraph.dir/community/walktrap/walktrap_graph.cpp.o src/CMakeFiles/igraph.dir/community/walktrap/walktrap_heap.cpp.o src/CMakeFiles/igraph.dir/community/walktrap/walktrap.cpp.o src/CMakeFiles/igraph.dir/connectivity/cohesive_blocks.c.o src/CMakeFiles/igraph.dir/connectivity/components.c.o src/CMakeFiles/igraph.dir/connectivity/separators.c.o src/CMakeFiles/igraph.dir/flow/flow.c.o src/CMakeFiles/igraph.dir/flow/st-cuts.c.o src/CMakeFiles/igraph.dir/hrg/hrg_types.cc.o src/CMakeFiles/igraph.dir/hrg/hrg.cc.o src/CMakeFiles/igraph.dir/io/dimacs.c.o src/CMakeFiles/igraph.dir/io/dl.c.o src/CMakeFiles/igraph.dir/io/dot.c.o src/CMakeFiles/igraph.dir/io/edgelist.c.o src/CMakeFiles/igraph.dir/io/graphml.c.o src/CMakeFiles/igraph.dir/io/gml-tree.c.o src/CMakeFiles/igraph.dir/io/gml.c.o src/CMakeFiles/igraph.dir/io/graphdb.c.o src/CMakeFiles/igraph.dir/io/leda.c.o src/CMakeFiles/igraph.dir/io/lgl.c.o src/CMakeFiles/igraph.dir/io/ncol.c.o src/CMakeFiles/igraph.dir/io/pajek.c.o src/CMakeFiles/igraph.dir/io/parse_utils.c.o src/CMakeFiles/igraph.dir/io/parsers/dl-lexer.c.o src/CMakeFiles/igraph.dir/io/parsers/dl-parser.c.o src/CMakeFiles/igraph.dir/io/parsers/gml-lexer.c.o src/CMakeFiles/igraph.dir/io/parsers/gml-parser.c.o src/CMakeFiles/igraph.dir/io/parsers/lgl-lexer.c.o src/CMakeFiles/igraph.dir/io/parsers/lgl-parser.c.o src/CMakeFiles/igraph.dir/io/parsers/ncol-lexer.c.o src/CMakeFiles/igraph.dir/io/parsers/ncol-parser.c.o src/CMakeFiles/igraph.dir/io/parsers/pajek-lexer.c.o src/CMakeFiles/igraph.dir/io/parsers/pajek-parser.c.o src/CMakeFiles/igraph.dir/layout/circular.c.o src/CMakeFiles/igraph.dir/layout/davidson_harel.c.o src/CMakeFiles/igraph.dir/layout/drl/DensityGrid.cpp.o src/CMakeFiles/igraph.dir/layout/drl/DensityGrid_3d.cpp.o src/CMakeFiles/igraph.dir/layout/drl/drl_graph.cpp.o src/CMakeFiles/igraph.dir/layout/drl/drl_graph_3d.cpp.o src/CMakeFiles/igraph.dir/layout/drl/drl_layout.cpp.o src/CMakeFiles/igraph.dir/layout/drl/drl_layout_3d.cpp.o src/CMakeFiles/igraph.dir/layout/fruchterman_reingold.c.o src/CMakeFiles/igraph.dir/layout/gem.c.o src/CMakeFiles/igraph.dir/layout/graphopt.c.o src/CMakeFiles/igraph.dir/layout/kamada_kawai.c.o src/CMakeFiles/igraph.dir/layout/large_graph.c.o src/CMakeFiles/igraph.dir/layout/layout_bipartite.c.o src/CMakeFiles/igraph.dir/layout/layout_grid.c.o src/CMakeFiles/igraph.dir/layout/layout_random.c.o src/CMakeFiles/igraph.dir/layout/mds.c.o src/CMakeFiles/igraph.dir/layout/merge_dla.c.o src/CMakeFiles/igraph.dir/layout/merge_grid.c.o src/CMakeFiles/igraph.dir/layout/reingold_tilford.c.o src/CMakeFiles/igraph.dir/layout/sugiyama.c.o src/CMakeFiles/igraph.dir/layout/umap.c.o src/CMakeFiles/igraph.dir/operators/add_edge.c.o src/CMakeFiles/igraph.dir/operators/complementer.c.o src/CMakeFiles/igraph.dir/operators/compose.c.o src/CMakeFiles/igraph.dir/operators/connect_neighborhood.c.o src/CMakeFiles/igraph.dir/operators/contract.c.o src/CMakeFiles/igraph.dir/operators/difference.c.o src/CMakeFiles/igraph.dir/operators/disjoint_union.c.o src/CMakeFiles/igraph.dir/operators/intersection.c.o src/CMakeFiles/igraph.dir/operators/misc_internal.c.o src/CMakeFiles/igraph.dir/operators/permute.c.o src/CMakeFiles/igraph.dir/operators/reverse.c.o src/CMakeFiles/igraph.dir/operators/rewire.c.o src/CMakeFiles/igraph.dir/operators/rewire_edges.c.o src/CMakeFiles/igraph.dir/operators/simplify.c.o src/CMakeFiles/igraph.dir/operators/subgraph.c.o src/CMakeFiles/igraph.dir/operators/union.c.o src/CMakeFiles/igraph.dir/paths/all_shortest_paths.c.o src/CMakeFiles/igraph.dir/paths/astar.c.o src/CMakeFiles/igraph.dir/paths/bellman_ford.c.o src/CMakeFiles/igraph.dir/paths/dijkstra.c.o src/CMakeFiles/igraph.dir/paths/distances.c.o src/CMakeFiles/igraph.dir/paths/eulerian.c.o src/CMakeFiles/igraph.dir/paths/floyd_warshall.c.o src/CMakeFiles/igraph.dir/paths/histogram.c.o src/CMakeFiles/igraph.dir/paths/johnson.c.o src/CMakeFiles/igraph.dir/paths/random_walk.c.o src/CMakeFiles/igraph.dir/paths/shortest_paths.c.o src/CMakeFiles/igraph.dir/paths/simple_paths.c.o src/CMakeFiles/igraph.dir/paths/sparsifier.c.o src/CMakeFiles/igraph.dir/paths/unweighted.c.o src/CMakeFiles/igraph.dir/paths/voronoi.c.o src/CMakeFiles/igraph.dir/paths/widest_paths.c.o src/CMakeFiles/igraph.dir/properties/basic_properties.c.o src/CMakeFiles/igraph.dir/properties/constraint.c.o src/CMakeFiles/igraph.dir/properties/convergence_degree.c.o src/CMakeFiles/igraph.dir/properties/dag.c.o src/CMakeFiles/igraph.dir/properties/degrees.c.o src/CMakeFiles/igraph.dir/properties/ecc.c.o src/CMakeFiles/igraph.dir/properties/girth.c.o src/CMakeFiles/igraph.dir/properties/loops.c.o src/CMakeFiles/igraph.dir/properties/multiplicity.c.o src/CMakeFiles/igraph.dir/properties/neighborhood.c.o src/CMakeFiles/igraph.dir/properties/perfect.c.o src/CMakeFiles/igraph.dir/properties/spectral.c.o src/CMakeFiles/igraph.dir/properties/trees.c.o src/CMakeFiles/igraph.dir/properties/triangles.c.o src/CMakeFiles/igraph.dir/isomorphism/bliss.cc.o src/CMakeFiles/igraph.dir/isomorphism/isoclasses.c.o src/CMakeFiles/igraph.dir/isomorphism/lad.c.o src/CMakeFiles/igraph.dir/isomorphism/isomorphism_misc.c.o src/CMakeFiles/igraph.dir/isomorphism/queries.c.o src/CMakeFiles/igraph.dir/isomorphism/vf2.c.o src/CMakeFiles/igraph.dir/misc/bipartite.c.o src/CMakeFiles/igraph.dir/misc/chordality.c.o src/CMakeFiles/igraph.dir/misc/cocitation.c.o src/CMakeFiles/igraph.dir/misc/coloring.c.o src/CMakeFiles/igraph.dir/misc/conversion.c.o src/CMakeFiles/igraph.dir/misc/cycle_bases.c.o src/CMakeFiles/igraph.dir/misc/degree_sequence.cpp.o src/CMakeFiles/igraph.dir/misc/embedding.c.o src/CMakeFiles/igraph.dir/misc/feedback_arc_set.c.o src/CMakeFiles/igraph.dir/misc/graphicality.c.o src/CMakeFiles/igraph.dir/misc/matching.c.o src/CMakeFiles/igraph.dir/misc/microscopic_update.c.o src/CMakeFiles/igraph.dir/misc/mixing.c.o src/CMakeFiles/igraph.dir/misc/motifs.c.o src/CMakeFiles/igraph.dir/misc/order_cycle.cpp.o src/CMakeFiles/igraph.dir/misc/other.c.o src/CMakeFiles/igraph.dir/misc/power_law_fit.c.o src/CMakeFiles/igraph.dir/misc/scan.c.o src/CMakeFiles/igraph.dir/misc/sir.c.o src/CMakeFiles/igraph.dir/misc/spanning_trees.c.o src/CMakeFiles/igraph.dir/internal/glpk_support.c.o src/CMakeFiles/igraph.dir/internal/hacks.c.o src/CMakeFiles/igraph.dir/internal/lsap.c.o src/CMakeFiles/igraph.dir/internal/qsort_r.c.o src/CMakeFiles/igraph.dir/internal/qsort.c.o src/CMakeFiles/igraph.dir/internal/utils.c.o src/CMakeFiles/igraph.dir/internal/zeroin.c.o src/CMakeFiles/igraph.dir/version.c.o  -Wl,-rpath,$BUILD_PREFIX/lib  $PREFIX/lib/libarpack.dylib  $PREFIX/lib/libblas.dylib  $PREFIX/lib/libglpk.dylib  $PREFIX/lib/libgmp.dylib  $PREFIX/lib/liblapack.dylib  $BUILD_PREFIX/lib/libxml2.dylib  $PREFIX/lib/libgmp.dylib  $PREFIX/lib/libomp.dylib && :
ld: warning: -pie being ignored. It is only used when linking a main executable
ld: warning: ignoring file $BUILD_PREFIX/lib/libxml2.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
```
I can't pretend to be an expert at building C libraries, let alone cross-compiling but I think the library should be coming from the host environment (where the OSX-ARM64 version is installed), not the build enviornment (`$BUILD_PREFIX`), where the OSX-64 version is installed).

**Comment by xylar** [comment]
@vtraag and @sodre, could you take a look at this as a replacement for #51?  It seems like `xmlEntity` has a new element in `libxml2 2.11` and is seems like OSX-ARM64 isn't finding the right `libxml2` shared library without some help.

**Comment by szhorvat** [comment]
@xylar I believe that the patch is not necessary and setting `-DIGRAPH_WARNINGS_AS_ERROR=OFF` should be sufficient.

If you come across something like this, please do open an issue for igraph. If I'd known about this yesterday, the fix could have been included in 0.10.5 🙂

**Comment by vtraag** [comment]
Thanks @xylar for taking care of this! The next version of the C core of igraph wil contain a similar fix.

@szhorvat, I would be in favour of keeping the patch in place, and not turn off treating warnings as errors. We will clearly know in a next release that the patch has become obsolete, since it won't be compatible with the new release anymore. However, we will most likely forget to turn on treating warnings as errors again in a next release. If we can keep treating warnings as errors this is useful information. If at some point we encounter too many issues with warnings, we can always turn it off.

**Review by vtraag — APPROVED** [review]

**Comment by xylar** [comment]
@szhorvat, I only started figuring this out yesterday pretty late but I appreciate you wanting an issue about this.

@vtraag, I was aware that you are also a developer in the source repo so I appreciate you seeing that the appropriate changes get made there.  I was somewhat counting on that but I'll make upstream issues in the future as well if I make any future PRs to this feedstock.

**Comment by xylar** [comment]
@vtraag, I'm not a maintainer so you'll have to merge this when you're happy (or wait for @sodre to approve if you prefer.)

**Comment by szhorvat** [comment]
I've already made the fix before I saw this thread, https://github.com/igraph/igraph/commit/5ad464be5ae2f6ebb69c97cb0140c800cc8d97d6

**Comment by vtraag** [comment]
> @vtraag, I'm not a maintainer

Thanks @xylar! Given your involvement and contributions, shall I add you to the maintainer list?

**Comment by xylar** [comment]
Sure, you can add me as a maintainer in #53 if you would like to.

**Comment by vtraag** [comment]
Ha, sorry, just already merged #53 before I saw this message. But will add you directly in `main`.

**Pull request merged**
