### PR TITLE
Update to version 0.8.0 and include support for Windows.

### PR DESCRIPTION
**Pull request by vtraag**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This PR updates `igraph` to version 0.8.0. Unlike PR #14, this also includes support for Windows. The support for Windows is submitted separately in this PR, so that if any issues present themselves, it doesn't conflict with the update to version 0.8.0 for other platforms, and PR #14 can still be merged.

There are hence two options: (1) all goes well, and we can merge this PR (in which case we should set the build number to 0); (2) problems galore, in which case PR #14 could simply be merged, and I continue working on this PR.

### CODE REVIEW

**Comment by vtraag** [comment]
@conda-forge-admin, please rerender

**Comment by vtraag** [comment]
It took some time, but I think option (1) should now be followed, and this PR should be favoured over PR #14. I have reset build number to 0, and this could be merged.

**Comment by vtraag** [comment]
@conda-forge-admin, please rerender

**Comment by vtraag** [comment]
Ping @sodre could you please take a look at this PR?

 I'd be happy to be added as a maintainer of this feedstock. I am currently commited to the development of the `igraph` project itself. Maintaining the `conda` feedstock would then only make sense from that perspective, and I am already a maintainer of `python-igraph`  [feedstock](https://github.com/conda-forge/python-igraph-feedstock).

**Comment by vtraag** [comment]
Note that this PR also fixes the issue addressed in PR #7, which can then also be closed.

**Comment by sodre** [comment]
@conda-forge-admin, please rerender

**Comment by sodre** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
